# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-26 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0002_remove_user_user_power'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermood',
            name='type_id',
        ),
        migrations.AddField(
            model_name='usermood',
            name='mood_title',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='usermood',
            name='mood_content',
            field=models.CharField(default='早晨起来拥抱太阳', max_length=256, null=True),
        ),
    ]
