# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-09-17 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0004_auto_20190830_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='user_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Theme_user', to='myBlog.User'),
        ),
    ]
