# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-09-17 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0005_auto_20190917_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermood',
            name='mood_secret',
            field=models.BooleanField(default=False),
        ),
    ]
