# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-09-25 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0007_secretmessage_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_type',
        ),
        migrations.AlterField(
            model_name='commit',
            name='committed_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commit_committed', to='myBlog.User'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Commit_blog_type', to='myBlog.BlogType'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Visitor_blog_type', to='myBlog.BlogType'),
        ),
        migrations.DeleteModel(
            name='ArticleType',
        ),
    ]
