# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-09-25 06:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0009_remove_article_article_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_blog_type',
        ),
    ]
