# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-09-26 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0010_remove_article_article_blog_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_qq',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
