# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-09-29 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0011_auto_20190926_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='type_id',
        ),
        migrations.AddField(
            model_name='commit',
            name='commit_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commit_commit', to='myBlog.User'),
        ),
    ]
