# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-09-29 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0012_auto_20190929_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commit',
            old_name='committed_user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='commit',
            old_name='commit_user',
            new_name='committer',
        ),
    ]
