# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-06 01:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0013_auto_20190929_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myBlog.Blog')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myBlog.User')),
            ],
            options={
                'db_table': 'blog_mark',
            },
        ),
    ]
