# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-11 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0014_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_agree',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_disagree',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
