# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-11 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0015_auto_20191111_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_author', to='myBlog.User'),
        ),
    ]
