# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-12 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0016_article_article_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_secret',
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_secret',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
