# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-12 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0017_auto_20191112_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_user',
            new_name='blog_author',
        ),
    ]
