# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-13 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0018_auto_20191112_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='author',
        ),
        migrations.AddField(
            model_name='commit',
            name='commit_stars',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
