# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-14 02:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0019_auto_20191113_0849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_suppose',
            new_name='article_bloged',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_top',
        ),
    ]
