# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-14 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0020_auto_20191114_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_secret',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
