# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-22 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0021_auto_20191114_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_top',
            field=models.BooleanField(default=False),
        ),
    ]
