# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-22 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0022_blog_blog_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtype',
            name='icon',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
