# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-25 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0024_auto_20191125_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemnotice',
            name='send_group',
        ),
        migrations.AddField(
            model_name='systemnotice',
            name='receive_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='接受组', to='myBlog.UserGroup'),
        ),
        migrations.AddField(
            model_name='systemnotice',
            name='system_notice_activate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemnotice',
            name='send_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='发送者', to='myBlog.Manager'),
        ),
    ]
