# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-25 06:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0025_auto_20191125_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemnotice',
            old_name='system_content',
            new_name='system_notice_content',
        ),
        migrations.RenameField(
            model_name='systemnotice',
            old_name='send_default',
            new_name='system_notice_default',
        ),
        migrations.RenameField(
            model_name='systemnotice',
            old_name='system_topic',
            new_name='system_notice_topic',
        ),
    ]
